window.PYDATA = {
  "fetchedAt": "2026-07-07 10:21",
  "quotes": {
    "usdjpy": 162.11,
    "nikkei": 69201.56,
    "dow": 53055.91,
    "nasdaq": 26121.16,
    "sox": 12900.14,
    "us10y": 4.48
  },
  "stockNewsText": "",
  "macroNewsText": "・今日の株式見通し＝買い先行、米ハイテク株高支え 次第に様子見か - Reuters\n  https://news.google.com/rss/articles/CBMigAFBVV95cUxObDFtZkVNREhkWERUTjFoZC0yRzZvTU9uY2JxSGxuZGpzRDBsb1VYdGhVWGdrdS1vbWtfWGo0RjNoMDlFVFA3WHRaaXNOMlhXQVA1RlpRTVlTelRvMXpQY2lVNU1pUlFucXhmSzhTcmYtNF9qbkQwZUFxcko0cnJvUw?oc=5\n・日経平均株価見通し：AI相場の変調と金利上昇のリスク、今週は変動拡大を警戒 - ig.com\n  https://news.google.com/rss/articles/CBMirgFBVV95cUxNWFpjU1diNG00bGRHZGRXbkhSTXJCdGMydEtfWS1CV203ZTBxSDVsMnZ6dmt2TTVidU50RllTTjh6cDRNdnpLTm14U0NKVV96eTNpWDRVU01BT3V2bmtCOXVSbTBpdHl5RmxWeGZNX0VXdXRRWV8xZnl1NUlmNXJNVkJVbThEamtfbDIxTWFVcmloMmJobFhNbER2dXFkNURvX29NR0pYallJal9aNWc?oc=5\n・日銀4月会合 利上げの“サイン”はあるのか？ 日銀短観と支店長会議報告から 野村證券・岩下真理 - nomura.co.jp\n  https://news.google.com/rss/articles/CBMiX0FVX3lxTE4wV1dxc3FIRTlMeHBfWWM5YW9GV3ZZUkxtTjNpY1BtaFEtQUhjVnlVRWxCZkJ4dm9tNGdUZGNrQ3ViOFc1aE5jODRHVHhscFJfbVVRWHJEb1VzazYzTkxz?oc=5\n・日銀が更に1％の利上げを予告？ 日銀審議委員の発言から見る、利上げの目標金利とスケジュール - 健美家\n  https://news.google.com/rss/articles/CBMia0FVX3lxTE9PLWJLNTRtcUdaMmdpaFhHQ2tyeF9vaFNIbHZvWGFIblRHZVZ5T3VLNENMRXFWVFEtRm16aVNOVWwza2dpVjBDQmE1eXpGNTFfS2pybXJKSG1odVUyTUVhMTNYZkhZVjFnZHpV?oc=5\n・AI投資はFRBに利上げを促すか？ インフレ圧力を高める可能性があると考える理由 野村證券・小清水直和 - nomura.co.jp\n  https://news.google.com/rss/articles/CBMiX0FVX3lxTE1jck1OaFIzUVowdVJINlBiWmF2WUNfYV9pZnhRaGJsM1hpRXRjMFFhd2h6dVd1LXlvUlhncHRzb2FOX2RDemVrc2dJdHJsNEpJZmhOb3ZXQkdfMFFYOTBZ?oc=5\n・先月のマーケットの振り返り（2026年6月） - smd-am.co.jp\n  https://news.google.com/rss/articles/CBMid0FVX3lxTE1DRjA2VnNMS29qejJpWkJNRDdOQ2p6Vm9UNUdRbnJqOEgzOUZZVTVTNVRnX1VpYkdRNXZ1aGowN2JONXVZREZxLTNVdlg2V2JxRWdrNS1RUzZaZVZLMHdvRXRfR0Q3Q3NoZmgwdXRlbkl5SzhkUF84?oc=5\n・ＮＹ外為市場＝ドル／円162円台前半、約40年ぶり円安圏 介入警戒続く - Reuters\n  https://news.google.com/rss/articles/CBMieEFVX3lxTE9NUjd0eGEwa3FPM1BiVkJTRzhPbEhWd2FELThYeS14Q05OenFzMkRjc2JpcDQzVG1sT0MzYkFBVGZrVWZQRDN5WHhhRTNuV0lua1J5NUF5V294eHNrTTQ4aW10TW8wMkZQUTdfYy1TWVJsNWx3b3JSLQ?oc=5\n・ゴールドマン、1ドル＝165円予想に転換－従来155円、キャリー取引選好（Bloomberg） - Yahoo!ニュース\n  https://news.google.com/rss/articles/CBMif0FVX3lxTE0xSVEtRnhhVGk2UjRFcDQzcDFzb29YLWVFNnJWb08xcVZOcVVNcjhvMFlMTUpLRktMZkRaOFlNbThDM1hKNER3UzJFOG93VHhpV0VjRmVHTDZXQW5YdWJzRlJjNFpOaURUcWxsanpvOGNUUE5ySmZyV3Y3LWlUZTQ?oc=5\n・米国株式市場、ＮＹダウ続伸し連日で最高値、ナスダック３日ぶり反発(ウエルスアドバイザー) - Yahoo!ファイナンス\n  https://news.google.com/rss/articles/CBMihwFBVV95cUxPalRhY3llcjI5amdiLWgzeENhYncxWGVLUnFDZlpVTk9WaVJJb1JkZU96UjUtX2FQdHBBZExMcXZuUkN2MzJ2RUhZZ1JOblc3U3ZMcG1PSU5Td05rQ3JQR1NlQ19FOTgySDNrdFNNR2VjVlRjOEhKQXE3UHZIb01tYWQybEtvelk?oc=5\n・米国株式市場＝Ｓ＆Ｐ・ナスダック大幅高、ブロードコムが上昇 - Reuters\n  https://news.google.com/rss/articles/CBMigAFBVV95cUxPMUJTS19PWU5ya1dPUHhzS1lXSUN4N092aEgzOWNnZnhYT1pkcXVEVi1qcERsV2tNd2pNYkRKRDQyRXozblJ5NkV0bmFtTF9VVnF4RjQzMEJORnJhc041RTN5RkdCMS04R0VqWm9Tc2lSbUFSM1RvZFNFMHRzSnJOMg?oc=5"
};
